trigger:
  - releases/*

jobs:
- job:
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  
  container: 'eosio/ci:ubuntu18'

  steps:
  
 # - task: GitHubRelease@0
 #   displayName: 'Edit GitHub Release'
 #   inputs: 
 #     - gitHubConnection: eosdublin 
 #   repositoryName: zenithworks/simplehtml
 #   action: edit
 #   tag: $(draftReleaseTag)
 #   assets: $(Build.ArtifactStagingDirectory)/distributableBinaries/*

  - script: git submodule update --init --recursive
    displayName: Initialize submodules
    
  - script: sed -i 's/"${MEM_MEG}" -lt 7000/"${MEM_MEG}" -lt 4000/g' scripts/eosio_build_ubuntu.sh
    displayName: Override EOS build script RAM check

#  - script: sed -i 's/\.\/bootstrap\.sh --prefix=\$BOOST_ROOT/\.\/bootstrap\.sh --prefix=\$BOOST_ROOT --with-toolset=clang/' scripts/eosio_build_ubuntu.sh
#    displayName: Force Boost compilation with clang

#  - script: sed -i 's/\&\& \$CMAKE -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=\$HOME \.\. \\/\&\& \$CMAKE -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=\$HOME -DCMAKE_CXX_COMPILER_ID=clang \.\. \\/' scripts/eosio_build_ubuntu.sh
#    displayName: Force MongoDB compilation with clang

  - script: scripts/eosio_build.sh -s EOS -y
    displayName: Build EOSIO

#  - script: chmod u+x build/packages/generate_package.sh && build/packages/generate_package.sh deb
#    displayName: Create DEB package

#  - script: cp build/packages/eosio_1.7.0-1_amd64.deb
#    displayName: Copy Artifact

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops
#  - task: GithubRelease@0 
#    displayName: 'Create GitHub Release'      
#    inputs:
#      githubConnection: eosdublin
#      repositoryName: eosdublin/eos
#      tagSource: manual
#      tag: $(Build.BuildNumber)      
#      assets: |
#           $(Build.ArtifactStagingDirectory)/*.deb
#           $(Build.ArtifactStagingDirectory)/README.txt

#resources:
#  containers:
#  - container: eosio_builder
#    image: ubuntu:18.04
#container: eosio_builder
